### ISSUE TITLE
'GruntLauncherPackage' package did not load correctly 

### ISSUE THREAD

**Issue by casperno** [Bjornej/GruntLauncher#39]
After updating to the latest version today (11 February 2015), GruntLauncher cannot load at all.
The xml log isn't very informative, I'm afraid:
Begin package load [GruntLauncherPackage] VisualStudio 2015/02/11 09:27:49.093 
726 ERROR CreateInstance failed for package [GruntLauncherPackage] 80070002 VisualStudio 2015/02/11 09:27:49.093 
727 ERROR End package load [GruntLauncherPackage]  80004005 - E_FAIL VisualStudio 2015/02/11 09:27:49.093

**Comment by lkt82** [comment]
I have the same issue :+1:

**Comment by Bjornej** [comment]
Sorry for the problem.

Can you try [this version](http://vsixgallery.com/extensions/cced4e72-2f8c-4458-b8df-4934677e4bf3/Grunt%20Launcher%20v1.7.2.vsix) and tell me if it solves the problem?

**Comment by casperno** [comment]
I've tried it and it did the trick! Thanks for resolving this issue so quickly.

Mange takk
