### ISSUE TITLE
Extension will not load in VS 2012 Pro

### ISSUE THREAD

**Issue by deantpt** [Bjornej/GruntLauncher#40]
Hello,
I've just loaded the extension and visual studio tells me it can't load it at launch. ActivityLog.xml shows (last section).

I saw an old post where i think a user reported something like this, extension looks great, would really appreciate your help

  <entry>
    <record>799</record>
    <time>2015/03/31 13:33:06.818</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{CCED4E72-2F8C-4458-B8DF-4934677E4BF3}</guid>
  </entry>
  <entry>
    <record>800</record>
    <time>2015/03/31 13:33:06.818</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [GruntLauncherPackage]</description>
    <guid>{CCED4E72-2F8C-4458-B8DF-4934677E4BF3}</guid>
  </entry>
  <entry>
    <record>801</record>
    <time>2015/03/31 13:33:06.829</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [GruntLauncherPackage]</description>
    <guid>{CCED4E72-2F8C-4458-B8DF-4934677E4BF3}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>802</record>
    <time>2015/03/31 13:33:06.829</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [GruntLauncherPackage]</description>
    <guid>{CCED4E72-2F8C-4458-B8DF-4934677E4BF3}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
</activity>

**Comment by Bjornej** [comment]
Hi!

It seems that the update to vs2013 broke the compatibility with vs2012. Can you confirm that you have only vs2012 installed on your machine and not vs2013?

If this is the case I'll install vs2012 in a VM  and see if I can solve the problem.

To be precise what version of VS2012 are you using?

**Comment by Bjornej** [comment]
I think I may have found a solution. Can you try [this test version](https://github.com/Bjornej/GruntLauncher/releases/download/1.7.5/GruntLauncher.vsix) and see if it works on your machine?

**Comment by deantpt** [comment]
Yes I did just have 2012 but I have just bought and installed 2013 for a number or reasons and its now working well

Thanks for the reply, and thanks for a great extension

**Comment by Bjornej** [comment]
Ok, I'll leave this issue open as I try to solve the problem.

**Comment by ytyukhnin** [comment]
Hi,
I was experiencing the same issue with the current NuGet version . And it seems that your fix works fine. Thank you.

**Comment by Bjornej** [comment]
@ytyukhnin Perfect can you confirm you had no other VS version installed(2013 or 2015)?

If this is the case I only need to test for VS2015 and this problem is solved

**Comment by ytyukhnin** [comment]
I confirm, no other version on the machine, VS 2012 only.

**Comment by Bjornej** [comment]
Published the fix on vs gallery. CLosing this issue
