### ISSUE TITLE
Bower install packages fails with 'ENOGIT git is not installed or not in the PATH'

### ISSUE THREAD

**Issue by sirtimbly** [Bjornej/GruntLauncher#41]
When I start up a brand new MVC project in VS2013 Update 4 I get this message 

```
Executing  

bower foundation5-sass#*        ENOGIT git is not installed or not in the PATH
```
Bower can't find Git from the context of the command line inside Visual Studio. Adding my local Git install to the path [like this issue on SO hints at](http://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path) fixed it for me. But, only after I closed and re-opened Visual Studio. So, I just wanted to document this issue here for others.

**Comment by Bjornej** [comment]
This is a common problem due to the way the windows command line works, as it reads the PATH variable only on startup. I can add a warning on the homepage to notify of the problem

**Comment by Bjornej** [comment]
Added the warning on the homepage. Closing this issue
