### ISSUE TITLE
'grunt' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by MikeVaz** [Bjornej/GruntLauncher#44]
I am using Visual Studio Version 12.0.30723.00 Update 3.

My grunt-cli is installed globally and I am able to run grunt from anywhere in the system except from Visual Studio using GruntLauncher.

This is what I am getting in Output: 

Executing Grunt: less 

'grunt' is not recognized as an internal or external command,

operable program or batch file.

**Comment by Bjornej** [comment]
This is strange as the extensions simply invokes grunt on the commandline.

I've seen times when installing grunt-cli globally with visual studio open will give the same error until VS is closed and reopened or after a restart as its inner console won't see THE new PATH variable.

Can you execute 'where grunt' on the commandline and tell me it's result?

**Comment by MikeVaz** [comment]
Results:

C:\Users...my project folder..>where grunt
C:\Users...my user...\AppData\Roaming\npm\grunt
C:\Users...my user...\Roaming\npm\grunt.cmd

**Comment by MikeVaz** [comment]
Did some extra research. And found out that something was wrong with my grunt installation. Because I was able to launch it only from my project folder where I have node_modules. So I reinstalled grunt-cli globally. After that restarted my system. And now the issue is gone. Probably something was wrong with my Path environment variable in the system.

**Comment by Bjornej** [comment]
Ok, no problem. I'm closing this issue as this was a in issue with your local grunt installation.
