### ISSUE TITLE
Task Runner Explorer

### ISSUE THREAD

**Issue by gilly3** [Bjornej/GruntLauncher#45]
Visual Studio 2015 ships with [Task Runner Explorer](http://webtooling.visualstudio.com/task-runners/gulp/#task-runner-explorer), which seems to offer functionality similar to this plugin.  Is there a reason to use this plugin vs the built-in functionality?

**Comment by Bjornej** [comment]
Mostly no, the built-in functionality covers almost everything you can do with this plugin.

I've created this plugin for VS2012 and later converted it to VS2013 when doing frontend development meant switching frequently to the commandline so I decided to simplify my workflow.

Now that VS embraced the standard node tools the plugin is no more necessary and I don't think I'll develop new features, unless someone aks.
